### ISSUE TITLE
OS X

### ISSUE THREAD

**Issue by oliviaguest** [dimpase/dyn#1]
This is what I get:

```
MBpro:dyn oliviaguest$ make runpy
python setup.py build_ext --inplace --rpath=.
running build_ext
skipping 'm.c' Cython extension (up-to-date)
python test.py
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    import dyn
ImportError: dlopen(/Users/oliviaguest/GitHub/dyn/dyn.so, 2): Library not loaded: libcmean.so
  Referenced from: /Users/oliviaguest/GitHub/dyn/dyn.so
  Reason: unsafe use of relative rpath libcmean.so in /Users/oliviaguest/GitHub/dyn/dyn.so with restricted binary
make: *** [runpy] Error 1
MBpro:dyn oliviaguest$ make runc
cc  main.c -o dync -L. -Wl,-rpath=. -lcmean
ld: unknown option: -rpath=.
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [dync] Error 1
```

**Comment by dimpase** [comment]
and what happens in `make runpy` if in the line of Makefile  
```
     python setup.py build_ext --inplace --rpath=.
``` 

you replace the last `=.` with `=/Users/oliviaguest/GitHub/dyn/` ? (or perhaps `="/Users/oliviaguest/GitHub/dyn/"`)

(you might have to do `make clean` first to initiate the complete rebuild)

**Comment by dimpase** [comment]
Another source of trouble here is that rather than installing this extension into the Python tree, something that normally would be done, we keep it separate, and this what OSX, in its infinite friendliness to developers, has a problem with.

**Comment by oliviaguest** [comment]
Unsurprisingly, this code works just fine on Mint.

**Comment by oliviaguest** [comment]
Could you point me to a good resource for installing this into the Python tree? I assume that that is why I am having trouble (even on Mint) importing my C/Cython library from a directory? 

When I try to import from a directory something with the same structure as dyn, in my case called pdist, I get ImportError. I added the directory pdist to the ```LD_LIBRARY_PATH``` to make it import correctly and it works, but I'm assuming this is not the best solution? See: https://github.com/oliviaguest/pdist/blob/master/README.md Do you know of a better/more appropriate way?

**Comment by oliviaguest** [comment]
PS: Sorry didn't mean to momentarily close this. :sweat_smile:

**Comment by dimpase** [comment]
It is possible to tweak `setup.py` to build `libcmean.so`; then,
assuming you are in a virtualenv, just run
```
python setup.py install
```
(you'd need sudo if you're playing with the systemwide python, naturally)

After this, 
```
python test.py
```
would work. I suppose I should provide such an example, too...
(naturally, pull requests are welcome, too)

**Comment by oliviaguest** [comment]
You mean this would install it in a way that doesn't require a specific directory structure?

**Comment by dimpase** [comment]
Typically the python extensions would go into something like `/usr/lib/python2.7/site-packages/`.

Another way would be to do the C part completely separately (I'd use autotools, i.e. autoconf/automake/libtool)
to create a sane cross-platform linking setup, and then link it to the cython extension in a normal way.
(this makes `setup.py` part easy, but more boilerplate would need on the C side)

**Comment by oliviaguest** [comment]
I think just for now, I'll keep it nasty with the way I did it. But if you do tweak ```setup.py``` or know what I need to read to do the above, let me know! :+1:

**Comment by oliviaguest** [comment]
Here's what OS X says with the change from . to the explicit path: 

```
MBpro:dyn oliviaguest$ make runpy
python test.py
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    import dyn
ImportError: dlopen(/Users/oliviaguest/GitHub/dyn/dyn.so, 2): Library not loaded: libcmean.so
  Referenced from: /Users/oliviaguest/GitHub/dyn/dyn.so
  Reason: unsafe use of relative rpath libcmean.so in /Users/oliviaguest/GitHub/dyn/dyn.so with restricted binary
make: *** [runpy] Error 1
```
